services:
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    volumes:
      - ../attachments:/app/attachments  # Sync attachments directory
      - ../src:/app/src  # Mount source code for live updates
    environment:
      - PYTHONPATH=/app
    env_file:
      - ../.env
      - .env
